{
 "title": "micro-obs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(api_requests_total , job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{job=\"$service\"}"
    }
   ]
  },
  {
   "title": "Apdex Score, 5m avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{job=~\"$service\", le=\"0.1\"}[5m])) by (job)+sum(rate(http_request_duration_seconds_bucket{job=~\"$service\", le=\"1\"}[5m])) by (job)) / 2 / sum(rate(http_request_duration_seconds_count{job=~\"$service\"}[5m])) by (job)"
    }
   ]
  },
  {
   "title": "P95, 5m avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(api_requests_total{job=\"$service\"})"
    }
   ]
  },
  {
   "title": "Current requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "in_flight_requests{job=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Avg response size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_response_size_bytes_sum{job=~\"$service\"} / http_response_size_bytes_count{job=~\"$service\"}"
    }
   ]
  },
  {
   "title": "P99, 5m avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(api_requests_total{job=\"$service\", code=~\"2[0-9]{2}\"})"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(api_requests_total{job=\"$service\", code=~\"4[0-9]{2}\"})"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(api_requests_total{job=\"$service\", code=~\"5[0-9]{2}\"})"
    }
   ]
  },
  {
   "title": "2xx Requests, 5m average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_total{job=\"$service\", code=~\"2[0-9]{2}\"}[5m])",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "4xx Requests, 5m average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_total{job=\"$service\", code=~\"4[0-9]{2}\"}[5m])",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "5xx Requests, 5m average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_total{job=\"$service\", code=~\"5[0-9]{2}\"}[5m])",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "Apdex Score (100ms, 1s), 5m avg",
   "type": "graph",
   "description": "Apdex score with target duration of 100ms and 1s acceptable duration. For more info visit https://en.wikipedia.org/wiki/Apdex",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_bucket{job=~\"$service\", le=\"0.1\"}[5m])) by (job)+sum(rate(http_request_duration_seconds_bucket{job=~\"$service\", le=\"1\"}[5m])) by (job)) / 2 / sum(rate(http_request_duration_seconds_count{job=~\"$service\"}[5m])) by (job)",
     "legendFormat": "{{$service}}"
    }
   ]
  },
  {
   "title": "Request rate, 5m avg, stacked",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request duration quantiles, 5m avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"$service\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Request duration, 5m average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{job=\"$service\"}[5m]) / rate(http_request_duration_seconds_count{job=\"$service\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}